"""Initial migration

Revision ID: 18555dae6e4c
Revises: a663257c8304
Create Date: 2024-06-21 16:31:08.515339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18555dae6e4c'
down_revision = 'a663257c8304'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('looking_word',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('paragraph_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['paragraph_id'], ['paragraph.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('word_history')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('word', sa.VARCHAR(length=100), nullable=False),
    sa.Column('article_id', sa.INTEGER(), nullable=False),
    sa.Column('paragraph_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['paragraph_id'], ['paragraph.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('looking_word')
    # ### end Alembic commands ###
