from .auth import auth_bp
from .reading_articles import reading_articles_bp
from .unfamiliar_word import unfamiliar_word_bp
from .stats import stats_bp
from .order import order_bp
from .paypal import paypal_bp
from .translate import translate_bp
from .user import user_bp
from .reading import reading_bp